/*
This code was autogenerated, 
it will regenerate with every change in blocks
*/
#include <application.h>

int button_click_count = 0;
int button_hold_count = 0;
twr_gfx_t *pgfx;
twr_led_t lcdLedRed;
twr_led_t lcdLedGreen;
twr_led_t lcdLedBlue;



void lcd_event_handler(twr_module_lcd_event_t event, void *param) {
	if (event == TWR_MODULE_LCD_EVENT_LEFT_PRESS) {
		twr_gfx_clear(pgfx);

		twr_gfx_set_font(pgfx, &twr_font_ubuntu_28);

		twr_gfx_draw_string(pgfx, 0, 0, "this is cool", true);

		twr_gfx_draw_rectangle(pgfx, 64, 64, 128, 128, true);

		twr_led_set_mode(&lcdLedRed, TWR_LED_MODE_TOGGLE);

		twr_gfx_update(pgfx);

		twr_gfx_draw_circle(pgfx, 64, 64, 20, true);

	}
	else if (event == TWR_MODULE_LCD_EVENT_RIGHT_PRESS) {
		twr_radio_pub_string("string", "STRING");

	}
}

void application_init(void) {
	twr_module_lcd_init();
	pgfx = twr_module_lcd_get_gfx();
	twr_gfx_set_font(pgfx, &twr_font_ubuntu_15);
	twr_gfx_draw_string(pgfx, 20, 50, "LCD WORKING", true);
	twr_gfx_update(pgfx);
	const twr_led_driver_t* driver = twr_module_lcd_get_led_driver();
	twr_led_init_virtual(&lcdLedRed, TWR_MODULE_LCD_LED_RED, driver, 1);
	twr_led_init_virtual(&lcdLedGreen, TWR_MODULE_LCD_LED_GREEN, driver, 1);
	twr_led_init_virtual(&lcdLedBlue, TWR_MODULE_LCD_LED_BLUE, driver, 1);
	twr_module_lcd_set_event_handler(lcd_event_handler, NULL);

	twr_radio_init(TWR_RADIO_MODE_NODE_LISTENING);
	twr_radio_pairing_request("test", "blockly_dev");

	twr_scheduler_plan_from_now(0, 1000);
}

void application_task(void) {
	twr_led_set_mode(&lcdLedBlue, TWR_LED_MODE_TOGGLE);

	twr_radio_pub_string("nice", "Helooo");

	twr_scheduler_plan_current_relative(1000);
}

