/*
This code was autogenerated, 
it will regenerate with every change in blocks
*/
#include <application.h>
#include <string.h>

float battery_voltage_value = 0;
int battery_percentage_value = 0;
twr_gfx_t *pgfx;
twr_led_t lcdLedRed;
twr_led_t lcdLedGreen;
twr_led_t lcdLedBlue;

char deviceID[] = "0-0";
char token[] = "";

void lcd_event_handler(twr_module_lcd_event_t event, void *param) {
	if (event == TWR_MODULE_LCD_EVENT_LEFT_PRESS) {
		twr_radio_pub_string("string", "STRING");

	}
	else if (event == TWR_MODULE_LCD_EVENT_RIGHT_PRESS) {
		twr_gfx_clear(pgfx);

		twr_led_set_mode(&lcdLedRed, TWR_LED_MODE_ON);

		twr_gfx_set_font(pgfx, &twr_font_ubuntu_15);
		
		char pillsPayload[] = "ibalgin:1,depress:2,viagra:4";
		char *token = strtok(pillsPayload, ",");
		int line = 1;
		
		while (token != NULL) {
			twr_log_info("%s\n", token);
			twr_gfx_draw_string(pgfx, 10, line*15, token, true);
        	token = strtok(NULL, ",");
			++line;
    	}
		twr_gfx_update(pgfx);
	}
	else if(event == TWR_MODULE_LCD_EVENT_LEFT_HOLD) {
		twr_led_set_mode(&lcdLedBlue, TWR_LED_MODE_BLINK_FAST);
		twr_radio_pub_string("registerDevice", deviceID);
	}
	else if (event == TWR_MODULE_LCD_EVENT_RIGHT_HOLD) {
		twr_led_blink(&lcdLedRed, 3);
		twr_gfx_clear(pgfx);
		twr_gfx_update(pgfx);
	}
}

void battery_event_handler(twr_module_battery_event_t event, void *event_param) {
	if (event == TWR_MODULE_BATTERY_EVENT_UPDATE) {
		float voltage;
		int percentage;
		if (twr_module_battery_get_voltage(&voltage) && twr_module_battery_get_charge_level(&percentage)) {
			battery_voltage_value = voltage;
			battery_percentage_value = percentage;
		}
	}
}

void TWR_MEDS_TAKE(uint64_t *id, const char *topic, void *value, void *param){
	char meds[20];
	strcpy(meds,value);

	char *token = strtok(meds, ",");
	int line = 1;
		
	while (token != NULL) {
		twr_log_info("%s\n", token);
		twr_gfx_draw_string(pgfx, 10, line*15, token, true);
		token = strtok(NULL, ",");
		++line;
	}

	twr_gfx_update(pgfx);
}

void HOUR_CHECK(){
	twr_led_set_mode(&lcdLedBlue, TWR_LED_MODE_TOGGLE);
	twr_radio_pub_string("check_hour", "now");
	twr_scheduler_plan_current_from_now(twr_tick_get() + 5000);
}

static const twr_radio_sub_t subs[] = {
	{"display/-/meds/show", TWR_RADIO_SUB_PT_STRING, TWR_MEDS_TAKE, NULL}
};

void application_init(void) {
	twr_log_init(TWR_LOG_LEVEL_DUMP, TWR_LOG_TIMESTAMP_ABS);
	twr_log_info("APPLICATION START");

	twr_module_lcd_init();
	pgfx = twr_module_lcd_get_gfx();
	twr_gfx_set_font(pgfx, &twr_font_ubuntu_15);
	twr_gfx_draw_string(pgfx, 20, 50, "LCD not working", true);
	twr_gfx_update(pgfx);
	const twr_led_driver_t* driver = twr_module_lcd_get_led_driver();
	twr_led_init_virtual(&lcdLedRed, TWR_MODULE_LCD_LED_RED, driver, 1);
	twr_led_init_virtual(&lcdLedGreen, TWR_MODULE_LCD_LED_GREEN, driver, 1);
	twr_led_init_virtual(&lcdLedBlue, TWR_MODULE_LCD_LED_BLUE, driver, 1);
	twr_module_lcd_set_event_handler(lcd_event_handler, NULL);

	twr_radio_init(TWR_RADIO_MODE_NODE_LISTENING);
	twr_radio_pairing_request("pills4U-dev", "blockly_dev");
	twr_radio_set_subs((twr_radio_sub_t *)subs, sizeof(subs)/ sizeof(twr_radio_sub_t));

	twr_module_battery_init();
	twr_module_battery_set_event_handler(battery_event_handler, NULL);
	twr_module_battery_set_update_interval(5000);

	twr_scheduler_register(HOUR_CHECK, NULL, twr_tick_get() + 5000);
}

void application_task(void) {
	// twr_led_set_mode(&lcdLedBlue, TWR_LED_MODE_TOGGLE);

	// twr_radio_pub_string("nice", "Helooo");

}

